### ISSUE TITLE
Azure DevOps Extension - Conan Package only contains sources after publish to Artifactory

### ISSUE THREAD

**Issue by wulfland** [jfrog/artifactory-azure-devops-extension#133]
I create a conan package in an Azure DevOps pipeline with the conan create task. 
```
- task: ArtifactoryConan@1
  displayName: 'Create Conan Package'
  inputs:
    conanCommand: 'Create'
    extraArguments: '--profile=$(conanProfile)'
    createPath: 'src'
    createReference: 'username/development'
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
```
Conan creates a package in the folder '.conan\data\packagename\1.1.0\user\development\package\3fb49604f9c2f729b85ba3115852006824e72cab\' that contains the lib and header files, a tgz archive, a conaninfo and conanmanifest. So everything looks good.

Put if I publish the package to Artifactory using the upload task, only the sources get uploaded
```
- task: ArtifactoryConan@1
  displayName: 'Upload Conan Package'
  inputs:
    conanCommand: 'Upload'
    patternOrReference: 'packagename'
    extraArguments: '--all --force'
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
```
I tried the --all and --force switch - but now my sources get uploaded two times. Am i Missing here something?
