### ISSUE TITLE
conanCommand: "upload", remoteName not evaluated

### ISSUE THREAD

**Issue by cpolzer** [jfrog/artifactory-azure-devops-extension#162]
Hi there,

when using the conan upload task, the remoteName is not taken into account for the upload. It seems always the last added remote is used.

When adding the remote to the  "extraArguments", it is working as expected.

Codeexample:

```
- task: ArtifactoryConan@1
  displayName: "Conan upload release repo"
  inputs: 
      conanCommand: "Upload"
      remoteName: "release" ## <- this is not recognized
      patternOrReference: "$(conan_package_name)/$(conan_package_version)@$(project_name)/$(conan_channel)"
      extraArguments: "--all -c -r release" ## <- this is working
      buildName: "$(Build.DefinitionName)"
      buildNumber: "$(Build.BuildNumber)"
      conanUserHome: "$(Pipeline.Workspace)"
```
