### ISSUE TITLE
noNuGetCache parameter value is not respected in nugetBuild.js

### ISSUE THREAD

**Issue by nholmes9** [jfrog/artifactory-azure-devops-extension#164]
Using the `tl.getInput()` method causes any value present for the `noNuGetCache` parameter evaluates to `true`, thereby not allowing the `-NoCache` CLI parameter to be suppressed.

https://github.com/jfrog/artifactory-azure-devops-extension/blob/1078431a18b2b6222cc74a2bc82bb2fd9de91e4c/tasks/ArtifactoryNuget/Ver2/nugetBuild.js#L143

The `tl.getBoolInput()` method should probably be used instead, as seen in the `runNuGet` method:
https://github.com/jfrog/artifactory-azure-devops-extension/blob/1078431a18b2b6222cc74a2bc82bb2fd9de91e4c/tasks/ArtifactoryNuget/Ver2/nugetBuild.js#L95

A workaround is to supply the `noNuGetCache`  parameter without a value, like so:
```yaml
  - task: JFrog.jfrog-artifactory-vsts-extension.artifactory-nuget.ArtifactoryNuGet@2
    displayName: "Restore packages"
    inputs:
      targetResolveRepo: nuget
      collectBuildInfo: true      
      noNuGetCache:
```
Using the above, `null` is evaluated to `false` and the the resulting command is:
`
##[debug]Executing cliCommand: C:\hostedtoolcache\windows\jfrog\1.35.5\x64\jfrog.exe rt nuget restore -Verbosity Detailed ...
`
