### ISSUE TITLE
Make ArtifactoryDocker not fail if image to pull doesn't exist

### ISSUE THREAD

**Issue by SimonAlling** [jfrog/artifactory-azure-devops-extension#166]
We're experimenting with pulling previously built images from Artifactory and use them as Docker build cache in our CI pipeline. Naturally, we use `ArtifactoryDocker` to pull the image:

```yaml
- task: ArtifactoryDocker@1
  displayName: Pull Docker image from Artifactory
  inputs:
    command: pull
    artifactoryService: $(ARTIFACTORY_SERVICE_CONNECTION)
    sourceRepo: $(ARTIFACTORY_DOCKER_REPO)
    imageName: $(IMAGE_NAME):99999999
```

This works like a charm. However, the task fails if the image doesn't exist (which will often be the case in practice), causing the pipeline to fail:

```
Login Succeeded
Error response from daemon: manifest for example.com/docker-images/foobar:99999999 not found: manifest unknown: The named manifest is not known to the registry.
[Error] exit status 1
```

We'd like to be able to specify something like `failOnMissing: false`, so that the task doesn't fail if the image to be pulled doesn't exist.
