### ISSUE TITLE
Is it possible to get the full reference name from a "conan create" to be used for "conan upload"?

### ISSUE THREAD

**Issue by thkowa** [jfrog/artifactory-azure-devops-extension#178]
I have a pipeline that has a "conan create" task. 

```
steps:
- task: JFrog.jfrog-artifactory-vsts-extension.artifactory-conan-build-task.ArtifactoryConan@1
  displayName: 'Conan Create'
  inputs:
    conanCommand: Create
    createPath: .
    createReference: sisu/testing
    extraArguments: '--profile linux-x64 -r virtual-conan'
```

My conan recipe evaluates the version number for the created package.

After the "conan create" task has run I want to upload the created package with a "conan upload" task. 

```
steps:
- task: JFrog.jfrog-artifactory-vsts-extension.artifactory-conan-build-task.ArtifactoryConan@1
  displayName: 'Conan Upload'
  inputs:
    conanCommand: Upload
    patternOrReference: full_ref ?????
    extraArguments: '--all -r virtual-conan'
```

The only problem is, that I do not know the full reference of the created recipe in order to pass that as "patternOrReference"
to the upload command.

Is there a way to get the full reference from the create command?
