### ISSUE TITLE
ArtifactoryMaven@2 task fails with `Error: Cannot find module 'azure-pipelines-task-lib/task'` on 2.10.4

### ISSUE THREAD

**Issue by moondowner** [jfrog/artifactory-azure-devops-extension#207]
Pipelines that were working are all failing now with the same error:

```
Starting: ArtifactoryMaven
==============================================================================
Task         : Artifactory Maven
Description  : Build with Apache Maven, while resolving dependencies and deploying artifacts from and to Artifactory and while allowing to collect build-info. The collected build-info can be later published to Artifactory by the "Artifactory Publish Build Info" task.
Version      : 2.10.4
Author       : JFrog
Help         : [More Information](https://www.jfrog.com/confluence/display/RTF/Maven+Repository)
==============================================================================
module.js:478
    throw err;
    ^

Error: Cannot find module 'azure-pipelines-task-lib/task'
    at Function.Module._resolveFilename (module.js:476:15)
    at Function.Module._load (module.js:424:25)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/vsts/work/_tasks/ArtifactoryMaven_07fc5c20-6772-11e5-abde-6901d3d00476/2.10.4/mavenBuild.js:1:72)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
##[error]Exit code 1 returned from process: file name '/home/vsts/agents/2.175.2/externals/node/bin/node', arguments '"/home/vsts/work/_tasks/ArtifactoryMaven_07fc5c20-6772-11e5-abde-6901d3d00476/2.10.4/mavenBuild.js"'.
Finishing: ArtifactoryMaven

```

Previously these pipelines were working with:

```
Version      : 2.10.2
```

The task that fails:

```
- task: ArtifactoryMaven@2
  displayName: Build and push docker images
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'package jib:build'
    artifactoryResolverService: 'Example'
    targetResolveReleaseRepo: 'repo'
    targetResolveSnapshotRepo: 'repo'
    artifactoryDeployService: 'Example'
    targetDeployReleaseRepo: 'repo'
    targetDeploySnapshotRepo: 'repo'
    options: -Dartifactory.publish.artifacts=false -Pinclude-metadata

```
