### ISSUE TITLE
Add ability to run `dotnet tool install`

### ISSUE THREAD

**Issue by arkiaconsulting** [jfrog/artifactory-azure-devops-extension#216]
**Is your feature request related to a problem? Please describe.**
For the moment, I'm unable to install a dotnet tool hosted in the Artifactory feed

**Describe the solution you'd like to see**
Additionally to `push` and `restore` commands, I would like to have a `tool install` command

**Describe alternatives you've considered**
I tried with the JfrogCli task, with no luck, as running a dotnet command under JfrogCli context requires 2 consecutive commands. But the JfrogCli context is reset at the end of each task.

**Additional context**

**Comment by Mrxx99** [comment]
Any solutions to that yet? @arkiaconsulting did you find a workaround?

**Comment by arkiaman** [comment]
@Mrxx99 Yes, but it's so ugly.... Here is the pipeline template:

```yaml
parameters:
  - name: ArtifactoryService
    type: string
  - name: ToolName
    type: string
  - name: ToolPath
    type: string
    default: $(Agent.TempDirectory)/
  - name: ArtifactoryDeployRepository
    type: string
  - name: AllowPreview
    type: boolean
    default: false
  - name: JfrogVersion
    type: string
    default: 1.53.1

steps:
  - task: JfrogCli@1
    displayName: Install Dotnet tool
    env:
      JFROG_DEPLOY_REPO: ${{ parameters.ArtifactoryDeployRepository }}
    inputs:
      artifactoryService: ${{ parameters.ArtifactoryService }}
      useCustomVersion: true
      cliVersion: ${{ parameters.JfrogVersion }}
      ${{ if eq(parameters['AllowPreview'], 'True') }}:
        command: |
          jfrog rt c show 2>&1
          cd $(Agent.ToolsDirectory)/jfrog/${JFROG_CLI_TASK_SELECTED_VERSION_AZURE}/x64
          server_id=`./jfrog rt c show 2>&1 | grep "Server ID:" | sed -n -E -e 's/^Server ID:[[:space:]]*(.*).*/\1/p'`
          echo ${server_id}
          ./jfrog rt dotnetc --repo-resolve ${JFROG_DEPLOY_REPO} --server-id-resolve ${server_id}
          ./jfrog rt dotnet tool install --global --prerelease --no-cache ${{ parameters.ToolName }}
          
      ${{ else }}:
        command: |
          jfrog rt c show 2>&1
          cd $(Agent.ToolsDirectory)/jfrog/${JFROG_CLI_TASK_SELECTED_VERSION_AZURE}/x64
          server_id=`./jfrog rt c show 2>&1 | grep "Server ID:" | sed -n -E -e 's/^Server ID:[[:space:]]*(.*).*/\1/p'`
          echo ${server_id}
          ./jfrog rt dotnetc --repo-resolve ${JFROG_DEPLOY_REPO} --server-id-resolve ${server_id}
          ./jfrog rt dotnet tool install --global --no-cache ${{ parameters.ToolName }}
```
